# Generated by Django 4.2.1 on 2023-05-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_response_contectnumber_alter_response_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contectNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
