# Generated by Django 4.2.1 on 2023-05-24 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_response_contectnumber_alter_response_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.question')),
            ],
        ),
    ]
